name: dio_receipe
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter_dotenv: ^6.0.0
  flutter_bloc: ^8.1.3
  http_mock_adapter: ^0.6.1
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.14.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
