name: Flutter CI/CD

on:
  push:
    branches: [main]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Create Env Files
        run: |
          echo "${{ secrets.ENV_PROD }}" > .env.prod
          touch .env.dev

      - name: Static Analysis
        run: flutter analyze

      - name: Run Tests
        run: flutter test

  build_prod_release:
    needs: test_and_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Create Env Files
        run: |
          echo "${{ secrets.ENV_PROD }}" > .env.prod
          touch .env.dev

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Build AppBundle (Prod)
        run: flutter build appbundle --release --flavor prod

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/prodRelease/app-prod-release.aab
